### PR TITLE
Adding Spinnaker Summit SIG Proposal

### PR DESCRIPTION
**Pull request by michaelgalloway**
Trying out the new SIG lifecycle process.  

This is a request for a new SIG to bring the community into the planning and discussions for the Spinnaker Summit.

### CODE REVIEW

**Comment by emjburns** [comment]
I have 0 authority but this seems like a great idea to me!

**Comment by aglover** [comment]
@spinnaker/sc FYI

**Comment by aglover** [comment]
+1. Looks good to me. I'm glad we're setting something up that facilitates community participation in the Summit.

**Comment by ajordens** [comment]
@michaelgalloway Can you include a link to a publicly accessible agenda doc.

**Comment by michaelgalloway** [comment]
Added @ajordens

**Comment by rmeshenberg** [comment]
+1.  Looks good.

**Comment by gcomstock** [comment]
LGTM

**Comment by aglover** [comment]
3 people of 5 from the SC have voted (+1) we therefore have a quorum.

**Comment by skim1420** [comment]
+1 (I believe I am #3?)

**Comment by gcomstock** [comment]
I just wanted to be wit the cool kids.

**Pull request merged**
